# Generated by Django 5.1 on 2025-03-17 05:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0014_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedEwaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectedewaste_weight', models.FloatField(default=0)),
                ('recyclable_weight', models.FloatField(default=0)),
                ('nonrecyclable_weight', models.FloatField(default=0)),
                ('rate_per_kg', models.FloatField(default=10)),
                ('total_amount', models.FloatField(default=100)),
                ('collectedewaste_date', models.DateField(default=django.utils.timezone.now)),
                ('Ewaste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.assignewastebooking')),
                ('yard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.yard')),
            ],
            options={
                'db_table': 'tbl_collectedewaste',
            },
        ),
    ]
